name: flutter_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3
  cloud_firestore: ^5.4.3
  provider: ^6.1.2 
  get_it: ^8.0.0
  file_picker: ^8.1.2
  flutter_spinkit: ^5.1.0 
  timeago: ^3.3.0
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
